# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Poptart Bracket 2020
email: james.ashworth@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  During the COVID-19 crazy times of 2020 a good friend of mine received a
  large shipment of cherry poptarts (128).  Her favorite flavor to be clear.  Then
  somewhere in her sugar induced state of euphoria she came up with this idea.
  This website is a documentary of the adventure she came up with.
baseurl: "/PoptartBracket2020" # the subpath of your site, e.g. /blog
url: "tonyashworth.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Tony_Ashworth
github_username:  TonyAshworth

defaults:
  - scope:
      path: "assets/img/submitted"
    values:
      bracket: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
